acescisat/urls.py
# default imports
from django.contrib import admin
from django.urls import include,path

# imports needed for static url pattern
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('theme.urls')),
	path('admin/', admin.site.urls),
	path('atlases/', include('atlases.urls')),
	path('climatology/', include('climatology.urls')),
	path('instruments/', include('instruments.urls')),
	path('meeting/', include('meeting.urls')),
	path('mission/', include('mission.urls')),
	path('molecules/', include('molecules.urls')),
	path('montreal/', include('montreal.urls')),
	path('publications/', include('publications.urls')),
    path('scenario/', include('scenario.urls')),
	path('science/', include('science.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

atlases/urls.py
from django.urls import path

# imports for static urls
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'atlases'
urlpatterns = [
    path('ace_atlas/', views.ace, name='ace'),
	path('solar_atlas/', views.solar, name='solar'),
]

climatology/urls.py
from django.urls import path

# imports for static urls
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'climatology'
urlpatterns = [
    path('', views.index, name='index'),
	path('climatology35', views.climatology35, name='climatology35'),
	path('climatology22', views.climatology22, name='climatology22'),
	path('climatology22NOy', views.climatology22NOy, name='climatology22NOy'),
]

instruments/urls.py
from django.urls import path

# imports for static urls
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'instruments'
urlpatterns = [
    path('', views.index, name='index'),
	path('fts', views.fts, name='fts'),
	path('maestro', views. maestro, name='maestro'),
	path('testing', views.testing, name='testing'),
]

meeting/urls.py
from django.urls import path

# imports for static urls
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'meeting'
urlpatterns = [
    path('', views.index, name='index'),
]

mission/urls.py
from django.conf.urls import url
from . import views

app_name = 'mission'
urlpatterns = [
	url('launch/', views.launch, name='launch'),
	url('orbit/', views.orbit, name='orbit'),
	url('', views.index, name='index'),
]

molecules/urls.py
from django.urls import path

# imports for static urls
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'molecules'
urlpatterns = [
    path('', views.index, name='index'),
    path('molecules35', views.molecules35, name='molecules35'),
    path('molecules30', views.molecules30, name='molecules30'),
    path('molecules22', views.molecules22, name='molecules22'),
    path('validation_O3', views.validation_O3, name='validation_O3'),
	path('<slug:molecule>', views.index, name='index'),
]

montreal/urls.py
from django.urls import path

from . import views

app_name = 'montreal'
urlpatterns = [
    path('', views.index, name='index')
]

publications/urls.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

try:
    from django.conf.urls import url
except ImportError:
    from django.conf.urls.defaults import url

from publications import views

app_name = 'publications'
urlpatterns = [
    url(r'^$', views.year, name='index'),
    url(r'^(?P<publication_id>\d+)/$', views.id, name='id'),
    url(r'^year/(?P<year>\d+)/$', views.year, name='year'),
    url(r'^tag/(?P<keyword>.+)/$', views.keyword, name='keyword'),
    url(r'^list/(?P<list>.+)/$', views.list, name='list'),
    url(r'^unapi/$', views.unapi, name='unapi'),
    url(r'^(?P<name>.+)/$', views.author, name='author'),
]

scenario/urls.py
from django.urls import path

# imports for static urls
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'scenario'
urlpatterns = [
    path('', views.index, name='index'),
]

science/urls.py
from django.urls import path
from . import views

app_name = 'science'
urlpatterns = [
    path('', views.index, name='index'),
	path('ozonedecline', views.ozonedecline, name='ozonedecline'),
    path('climatechange', views.climatechange, name='climatechange'),
    path('ozonemonitoring', views.ozonemonitoring, name='ozonemonitoring'),
    path('dataanalysis', views.dataanalysis, name='dataanalysis'),
    path('scienceresults', views.scienceresults, name='scienceresults'),
]

theme/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
	path('acknowledgment/', views.acknowledgment, name='acknowledgment'),
]

urls.py
from django.urls import path

# imports for static urls
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'scenario'
urlpatterns = [
    path('', views.index, name='index'),
]

atlases/models.py
from django.db import models

# Create your models here.

meeting/models.py
from django.db import models

# Create your models here.

mission/models.py
from django.db import models

# Create your models here.

atlases/views.py
from django.shortcuts import render_to_response
import os

# Create your views here.
app_name = 'atlases'
def solar(request):
	return render_to_response(os.path.join('atlases','solaratlas.html'))
	
def ace(request):
	return render_to_response(os.path.join('atlases','aceatlas.html'))

meeting/views.py
from django.shortcuts import render_to_response
import os

# Create your views here.
def index(request):
	return render_to_response(os.path.join('meeting','index.html'))

mission/views.py
from django.shortcuts import render, render_to_response
import os

# Create your views here.
def index(request):
    return render_to_response(os.path.join('mission','index.html'))
	
def orbit(request):
    return render_to_response(os.path.join('mission','orbit.html'))
	
def launch(request):
    return render_to_response(os.path.join('mission','launch.html'))

montreal/views.py
from django.shortcuts import render_to_response
import os

# Create your views here.

def index(request):
	return render_to_response(os.path.join('montreal','index.html'))

scenario/views.py
from django.shortcuts import render, render_to_response
import os

################################
# Create your views here.

def index(request):
    return render_to_response(os.path.join('scenario','index.html'))

science/views.py
from django.shortcuts import render_to_response
import os

# Create your views here.

def index(request):
	return render_to_response(os.path.join('science','index.html'))
	
def ozonedecline(request):
	return render_to_response(os.path.join('science','ozonedecline.html'))
	
def climatechange(request):
	return render_to_response(os.path.join('science','climatechange.html'))
	
def ozonemonitoring(request):
	return render_to_response(os.path.join('science','ozonemonitoring.html'))
	
def dataanalysis(request):
	return render_to_response(os.path.join('science','dataanalysis.html'))
	
def scienceresults(request):
	return render_to_response(os.path.join('science','scienceresults.html'))

theme/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'theme/home.html')

def acknowledgment(request):
    return render(request, 'theme/acknowledgment.html')

views.py
from django.shortcuts import render_to_response
import os

# Create your views here.
def index(request):
	return render_to_response(os.path.join())

theme/templates/theme/acknowledgment.html
{% extends "theme/base.html" %}
{% load staticfiles %}

<title>{% block title %}ACE/SCISAT - The Atmospheric Chemistry Experiment - Acknowledgment{% endblock title %}</title>

{% block breadcrumb__links %}
  <li class="breadcrumb__primary"><a href="{% url 'home:index' %}">Home</a></li>
  <li class="breadcrumb__addon"><i class="fa fa-angle-double-right"></i></li>
  <li class="breadcrumb__addon"><span><a href="{% url 'home:acknowledgment' %}">Acknowledgment</a></span></li>
{% endblock breadcrumb__links %}

{% block content %}
<h2>Acknowledgment</h2>
<br>
<div class="grid grid--full grid--gutters large-grid--fit">
    <div class="grid__cell" id="popout">
        <p>The Atmospheric Chemistry Experiment (ACE), also known as SCISAT, is a Canadian-led mission mainly supported by the Canadian Space Agency (CSA).
        </p>
    </div>
</div>
{% endblock content %}

theme/templates/theme/base.html
<!doctype html>
{% load staticfiles %}
<html class="no-js {% block html_class %}{% endblock html_class %}" lang="en-CA">
    <head>
        {% block head %}
		{% block fonts %}
        <script type="text/javascript" src="https://fast.fonts.com/jsapi/9c101523-c9e9-4e52-b751-a5b16576f638.js"></script>
        {% endblock fonts %}
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="ACE/SCISAT - The Atmospheric Chemistry Experiment">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="{% static "/theme/img/favicon.ico" %}">
        {% block default_styles %}
        <link href="{% static "theme/css/main.css" %}" rel="stylesheet" type="text/css">
        {% endblock default_styles %}
        
        {% endblock head %}
        {% block head_addon_bottom %}{% endblock head_addon_bottom %}
    </head>
    <body class="site {% block body_class %}{% endblock body_class %}">
        {% block header %}
        <header class="grid {% block header_class %}{% endblock header_class %}">
             {% block logo %}<a class="logo" href="{% url 'home:index' %}"><img id="logo" src="{% static "theme/img/banner_acescisat.png" %}"/></a>{% endblock logo %}
             {% block banner_title %}
             <div class="aligner">
                <div class="aligner__item banner-title"><a href="{% url 'home:index' %}">The Atmospheric Chemistry Experiment</a></div>
             </div>
             {% endblock banner_title %}
             <div class="grid__cell grid-cell--center align-right">
                 <a class="off-canvas-nav" href="#off-canvas"><i class="fa fa-bars navicon"></i></a>
                 <a class="off-canvas-nav" href="#"><i class="fa fa-times navicon"></i></a>
             </div>
        </header><!-- .end / HEADER -->
        {% endblock header %}
        {% block breadcrumb %}
        <nav class="grid {% block bread_class %}{% endblock bread_class %}">
            <div class="grid__cell grid-cell--center">
                <ul class="breadcrumb">
                  {% block breadcrumb__links %}
                  {% endblock breadcrumb__links %}
                </ul>
            </div>
        </nav><!-- .end / NAV -->
        {% endblock breadcrumb %}
        <main class="site-content styleguide {% block main_class %}{% endblock main_class %}">
          {% block content %}
          {% endblock content %}
        </main><!-- .end / MAIN -->
        {% block footer %}
        <footer class="no-cl {% block footer_class %}{% endblock footer_class %}">
          <div class="grid grid--full grid--gutters large-grid--fit">
              <div class="grid__cell">
                  <ul class="contact">
                    <li><p class="footer__list-title">Contact Us:</p></li>
					<li><a href="mailto:info@scisat.ca"><i class="fa fa-envelope-square"></i></a><li>
					<li><a href="https://twitter.com/scisat"><i class="fa fa-twitter-square"></i></a></li>
                  </ul>
              </div>
              <div class="grid__cell">
              </div>
          </div>
        </footer><!-- .end / FOOTER -->
        <div class="off-canvas" id="off-canvas">
		  <ul>
		    <li class="open-nav">
            <a class="off-canvas-toggle" href="#off-canvas">
			<i class="fa fa-bars navicon" style="pointer-events: none;"></i>
			<span class='nav-text'> </span>
			</a>
			</li>
			
			<li class="close-nav">
            <a class="off-canvas-toggle" href="#">
			<i class="fa fa-times navicon" style="pointer-events: none;"></i>
			<span class='nav-text' style='left: 13px;'>Close Navigation</span>
			</a>
			</li>
			
			<div class='nav-category'>
			<li>
			<a class='nav-link' href="{% url 'home:index' %}">
			<i class="fa fa-home"></i>
			<span class='nav-text'>Home</span>
			</a>
			<ul class='sub-menu'>
				<li>
				<a class='nav-link' href="{% url 'home:acknowledgment' %}">
				<span class='nav-text'>Acknowledgment</span>
				</a>
				</li>
				</ul>
			</li>
			</div>
			
			<div class='nav-category'>
				<li>
				<a class='nav-link' href="{% url 'mission:index' %}">
				<i class="fa fa-rocket"></i>
				<span class='nav-text'>Mission</span>
				</a>
				<ul class='sub-menu'>
					<li>
					<a class='nav-link' href="{% url 'mission:launch' %}">
					<span class='nav-text'>Launch</span>
					</a>
					</li>
					
					<li>
					<a class='nav-link' href="{% url 'mission:orbit' %}">
					<span class='nav-text'>Orbit</span>
					</a>
					</li>
				</ul>
				</li>
			</div>
			
			<div class='nav-category'>
			<li>
			<a class='nav-link' href="{% url 'science:index' %}">
			<i class="fa fa-flask"></i>
			<span class='nav-text'>Science</span>
			</a>
			</li>
			<ul class='sub-menu'>
				<li>
				<a class='nav-link' href="{% url 'science:ozonedecline' %}">
				<span class='nav-text'>Ozone Decline</span>
				</a>
				</li>
				
				<li>
				<a class='nav-link' href="{% url 'science:climatechange' %}">
				<span class='nav-text'>Climate Change</span>
				</a>
				</li>
				
				<li>
				<a class='nav-link' href="{% url 'science:ozonemonitoring' %}">
				<span class='nav-text'>Ozone Monitoring</span>
				</a>
				</li>
				
				<li>
				<a class='nav-link' href="{% url 'science:dataanalysis' %}">
				<span class='nav-text'>Data Analysis</span>
				</a>
				</li>
				
				<li>
				<a class='nav-link' href="{% url 'science:scienceresults' %}">
				<span class='nav-text'>Science Results</span>
				</a>
				</li>
			</ul>
			</div>
			
			
			<div class='nav-category'>
				<li>
				<a class='nav-link' href="{% url 'instruments:index' %}">
				<i class="fa fa-cog"></i>
				<span class='nav-text'>Instruments</span>
				</a>
				<ul class='sub-menu'>
					<li>
					<a class='nav-link' href="{% url 'instruments:fts' %}">
					<span class='nav-text'>ACE-FTS</span>
					</a>
					</li>
					
					<li>
					<a class='nav-link' href="{% url 'instruments:maestro' %}">
					<span class='nav-text'>MAESTRO</span>
					</a>
					</li>
					
					<li>
					<a class='nav-link' href="{% url 'instruments:testing' %}">
					<span class='nav-text'>Testing</span>
					</a>
					</li>
				</ul>
				</li>
			</div>
			
			<div class='nav-category'>
			<li>
			<a class='nav-link' href="{% url 'molecules:index' %}">
			<i class="nav-text-icon">O<sub>3</sub></i>
			<span class='nav-text' style='position: relative; top:-2px;'>Molecules</span>
			</a>
			<ul class='sub-menu'>
					<li>
					<a class='nav-link' href="{% url 'molecules:molecules22' %}">
					<span class='nav-text'>V2.2 MW List</span>
					</a>
					</li>
					
					<li>
					<a class='nav-link' href="{% url 'molecules:molecules30' %}">
					<span class='nav-text'>V3.0 MW list</span>
					</a>
					</li>
					
					<li>
					<a class='nav-link' href="{% url 'molecules:molecules35' %}">
					<span class='nav-text'>V3.5 MW list</span>
					</a>
					</li>
					
					<li>
					<a class='nav-link' href="{% url 'molecules:validation_O3' %}">
					<span class='nav-text'>O<sub>3</sub> Validation</span>
					</a>
					</li>
				</ul>
			</li>
			</div>

			
			<li>
			<a class='nav-link' href="{% url 'publications:index' %}">
			<i class="fa fa-file-powerpoint-o"></i>
			<span class='nav-text'>Publications</span>
			</a>
			</li>
			
			<li>
			<a class='nav-link' href="{% url 'home:index' %}">
			<i class="fa fa-picture-o"></i>
			<span class='nav-text'>Gallery</span>
			</a>
			</li>
			
			<li>
			<a class='nav-link' href="https://databace.scisat.ca/">
			<i class="fa fa-folder-o"></i>
			<span class='nav-text'>Data</span>
			</a>
			</li>
			
			<li>
			<a class='nav-link' href="{% url 'scenario:index' %}">
			<i class="fa fa-globe"></i>
			<span class='nav-text'>Scenario</span>
			</a>
			</li>
			
			<div class='nav-category'>
				<li>
				<a class='nav-link' href="{% url 'atlases:ace' %}">
				<i class="fa fa-book"></i>
				<span class='nav-text'>Atlases</span>
				</a>
				<ul class='sub-menu'>
					<li>
					<a class='nav-link' href="{% url 'atlases:ace' %}">
					<span class='nav-text'>ACE Atlas</span>
					</a>
					</li>
					
					<li>
					<a class='nav-link' href="{% url 'atlases:solar' %}">
					<span class='nav-text'>Solar Atlas</span>
					</a>
					</li>
				</ul>
				</li>
			</div>
			
			<div class='nav-category'>
			<li>
			<a class='nav-link' href="{% url 'climatology:index' %}">
			<i class="fa fa-cloud"></i>
			<span class='nav-text'>Climatology</span>
			</a>
			<ul class='sub-menu'>
				<li>
				<a class='nav-link' href="{% url 'climatology:climatology35' %}">
				<span class='nav-text'>Climatology V3.5</span>
				</a>
				</li>
				
				<li>
				<a class='nav-link' href="{% url 'climatology:climatology22' %}">
				<span class='nav-text'>Climatology V2.2</span>
				</a>
				</li>
				
				<li>
				<a class='nav-link' href="{% url 'climatology:climatology22NOy' %}">
				<span class='nav-text'>Climatology V2.2NOy</span>
				</a>
				</li>
			</ul>
			</li>
			
			
			</div>
			<li>
			<a class='nav-link' href="http://bernath.uwaterloo.ca/molecularlists.php">
			<i class="fa fa-list"></i>
			<span class='nav-text'>Mollist</span>
			</a>
			</li>
			
			<li>
			<a class='nav-link' href="{% url 'home:index' %}">
			<i class="fa fa-area-chart"></i>
			<span class='nav-text'>Daily Plots</span>
			</a>
			</li>
			
			<li>
			<a class='nav-link' href="{% url 'meeting:index' %}">
			<i class="fa fa-users"></i>
			<span class='nav-text'>ACE Meeting</span>
			</a>
			</li>
			
			<li>
			<a class='nav-link' href="{% url 'montreal:index' %}">
			<img class='maple-leaf' src="{% static "theme/img/maple-leaf3.png" %}">
			<span class='nav-text' style='position: relative; top:-10px; left: 15px;'>Montreal Protocol</span>
			</a>
			</li>
		  </ul>
        </div>
        {% endblock footer %}
        {% block footer_js %}
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script src="{% static "theme/js/min/scripts.js" %}"></script>
        {% endblock footer_js %}
        {% block footer_addon_js %}{% endblock footer_addon_js %}
    </body><!-- .end / BODY -->
</html>

theme/templates/theme/home.html
{% extends "theme/base.html" %}
{% load staticfiles %}

<title>{% block title %}ACE/SCISAT - The Atmospheric Chemistry Experiment{% endblock title %}</title>

{% block head_addon_bottom %}
<script src="{% static "Scenario/Build/Cesium/Cesium.js" %}"></script>
<style>
@import url({% static "Scenario/Build/Cesium/Widgets/widgets.css" %});
#cesiumContainer {
width: 100%; 
height: 100%; 
margin: 0; 
padding: 0;
border: 0px solid black;
overflow: hidden;
</style>
{% endblock head_addon_bottom %}

{% block breadcrumb__links %}
  <li class="breadcrumb__primary"><a href="{% url 'home:index' %}">Home</a></li>
{% endblock breadcrumb__links %}

{% block content %}
<h2 style="text-align: center; padding-bottom: 10px;">Welcome to the homepage for the Atmospheric Chemistry Experiment</h2>
<div class="container-home">
    <div class="grid__cell">
		<!--<img class="testlogo" src="{% static "theme/img/ScisatLogo.png" %}" alt="SCISATlogo"">-->
        <p> The Atmospheric Chemistry Experiment (ACE) is a satellite mission on board the Canadian satellite SCISAT, that takes measurements of the Earth's atmosphere. </p> 
		<p> The measurements consist of spectra and images that are used to investigate chemical and dynamical processes in our atmosphere, with a particular emphasis on ozone depletion in the Arctic stratosphere. </p>
		<p>Dr. Peter Bernath from the Department of Chemistry at the University of Waterloo is the Mission Scientist, which involves the collaboration of members from several universities, industries and other organizations in Canada and around the world.</p>
    </div>
	<div id="cesiumContainer" class="grid__cell" style="border:2px solid grey;">
		<script>
		//update bing maps key
		Cesium.BingMapsApi.defaultKey = 'fWDgSzttTLCbHpbQeLpm~W5ZFSEAonrWmUztoNDYgfw~ApalPOynk04hBOe_vHhA5ojCRE42tXmr9RpqjXUztU_Qj32Fk2mzDqpIczorn8FO';
		
		// code to create viewer, set scene and try and optimize frame rate
		var viewer = new Cesium.Viewer('cesiumContainer', {
			//sceneMode: Cesium.SceneMode.SCENE2D
			fxaa: false,
			timeline: false,
			imageryProvider: new Cesium.BingMapsImageryProvider({
				url : 'https://dev.virtualearth.net',
				mapStyle : Cesium.BingMapsStyle.AERIAL_WITH_LABELS
			}),
			baseLayerPicker : false,
			fullscreenButton : false,
			homeButton : false,		
		});
		
		//Configures various viewer settings
		//viewer.scene.debugShowFramesPerSecond = true;
		viewer.resolutionScale = 1.0 / devicePixelRatio;
		//viewer.fullscreenButton = false;
		viewer.navigationInstructionsInitiallyVisible = false;
		//viewer.timeline = false;
		viewer.scene.fxaa = false;
		
		// code to import current czml file
		var czmlSource = new Cesium.CzmlDataSource();
		var czmlFile = "{% static "Scenario/scisatLive.czml" %}";
		czmlSource.load(czmlFile);
		viewer.dataSources.add(czmlSource);
		
		// code to follow scisat, after CZML load promise is finished
		czmlSource.load(czmlFile).then(function(){
			//clearLoader();
			var scisat1 = czmlSource.entities.getById("Satellite/Scisat1");
			var camera = viewer.camera;
			
			
			// Updates time to be real time
			var clock = viewer.clock;
			clock.clockStep = Cesium.ClockStep.SYSTEM_CLOCK;
			var curTime = clock.currentTime;

			// Tracks satellite with a defined camera angle to start
			var s1Position = scisat1.position.getValue(curTime);
			var cameraPosition = s1Position;
			//var cameraOffset = s1Position;
			//console.log(cameraOffset)
			//cameraOffset.z = cameraOffset.z - 100;
			//scisat1.viewFrom = cameraOffset;
			scisat1.viewFrom = Cesium.Cartesian3.fromElements(-4.0,2.50,7.00) //Spherical coordinates for (45,-45)
			//scisat1.viewFrom = Cesium.Cartesian3.fromDegrees(-45,45,10);
			//console.log(scisat1.viewFrom);
			//console.log(cameraOffset);
			viewer.trackedEntity = scisat1;
			//console.log(cameraOffset);
			//console.log(s1Position);
		});
		</script>
	</div>
</div>
{% endblock content %}