acescisat/urls.py
# default imports
from django.contrib import admin
from django.urls import include,path

# imports needed for static url pattern
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('theme.urls')),
	path('admin/', admin.site.urls),
	path('atlases/', include('atlases.urls')),
	path('climatology/', include('climatology.urls')),
	path('instruments/', include('instruments.urls')),
	path('meeting/', include('meeting.urls')),
	path('mission/', include('mission.urls')),
	path('molecules/', include('molecules.urls')),
	path('montreal/', include('montreal.urls')),
	path('publications/', include('publications.urls')),
    path('scenario/', include('scenario.urls')),
	path('science/', include('science.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

publications/urls.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

try:
    from django.conf.urls import url
except ImportError:
    from django.conf.urls.defaults import url

from publications import views

app_name = 'publications'
urlpatterns = [
    url(r'^$', views.year, name='index'),
    url(r'^(?P<publication_id>\d+)/$', views.id, name='id'),
    url(r'^year/(?P<year>\d+)/$', views.year, name='year'),
    url(r'^tag/(?P<keyword>.+)/$', views.keyword, name='keyword'),
    url(r'^list/(?P<list>.+)/$', views.list, name='list'),
    url(r'^unapi/$', views.unapi, name='unapi'),
    url(r'^(?P<name>.+)/$', views.author, name='author'),
]

urls.py
from django.urls import path

# imports for static urls
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'scenario'
urlpatterns = [
    path('', views.index, name='index'),
]

publications/models/customfile.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.db import models
from publications.models import Publication

class CustomFile(models.Model):
	class Meta:
		app_label = 'publications'

	publication = models.ForeignKey(Publication,models.CASCADE)
	description = models.CharField(max_length=256)
	file = models.FileField(upload_to='publications/custom/')

	def __unicode__(self):
		return self.description

	def __str__(self):
		return self.description

publications/models/customlink.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.db import models
from publications.models import Publication

class CustomLink(models.Model):
	class Meta:
		app_label = 'publications'

	publication = models.ForeignKey(Publication, models.CASCADE)
	description = models.CharField(max_length=256)
	url = models.URLField(verbose_name='URL')

	def __unicode__(self):
		return self.description

	def __str__(self):
		return self.description

publications/models/list.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.db import models

class List(models.Model):
	"""
	Model representing a list of publications.
	"""

	class Meta:
		app_label = 'publications'
		ordering = ('list',)
		verbose_name_plural = 'Lists'

	list = models.CharField(max_length=128)
	description = models.CharField(max_length=128)

	def __unicode__(self):
		return self.list

	def __str__(self):
		return self.list

publications/models/publicationlist.py
class PublicationsPublicationLists(models.Model):
	id = models.AutoField(primary_key=True)
    publication = models.ForeignKey('PublicationsPublication', models.DO_NOTHING)
    list = models.ForeignKey('PublicationsList', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'publications_publication_lists'
        unique_together = (('publication', 'list'),)

publications/views/author.py
# -*- coding: utf-8 -*-

__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from collections import defaultdict
from django.shortcuts import render
from string import capwords

from publications.models import Type, Publication, CustomLink, CustomFile
from publications.utils import populate


def author(request, name):
    fullname = capwords(name.replace('+', ' '))
    fullname = fullname.replace(' Von ', ' von ').replace(' Van ', ' van ')
    fullname = fullname.replace(' Der ', ' der ')

    # take care of dashes
    off = fullname.find('-')
    while off > 0:
        off += 1
        if off <= len(fullname):
            fullname = fullname[:off] + fullname[off].upper() + fullname[off + 1:]
        off = fullname.find('-', off)

    # split into forename, middlenames and surname
    names = name.replace(' ', '+').split('+')

    # construct a liberal query
    surname = names[-1]
    surname = surname.replace(u'ä', u'%%')
    surname = surname.replace(u'ae', u'%%')
    surname = surname.replace(u'ö', u'%%')
    surname = surname.replace(u'oe', u'%%')
    surname = surname.replace(u'ü', u'%%')
    surname = surname.replace(u'ue', u'%%')
    surname = surname.replace(u'ß', u'%%')
    surname = surname.replace(u'ss', u'%%')

    query_str = u'SELECT * FROM {table} ' \
                'WHERE lower({table}.authors) LIKE lower(\'%%{surname}%%\') ' \
                'ORDER BY {table}.year DESC, {table}.month DESC, {table}.id DESC'
    query = Publication.objects.raw(
        query_str.format(table=Publication._meta.db_table, surname=surname))

    # find publications of this author
    publications = []
    publications_by_type = defaultdict(lambda: [])

    # further filter results
    if len(names) > 1:
        name_simple = Publication.simplify_name(names[0][0] + '. ' + names[-1])
        for publication in query:
            if name_simple in publication.authors_list_simple:
                publications.append(publication)
                publications_by_type[publication.type_id].append(publication)

    elif len(names) > 0:
        for publication in query:
            if Publication.simplify_name(names[-1].lower()) in publication.authors_list_simple:
                publications.append(publication)
                publications_by_type[publication.type_id].append(publication)

    # attach publications to types
    types = Type.objects.filter(id__in=publications_by_type.keys())
    for t in types:
        t.publications = publications_by_type[t.id]

    if 'plain' in request.GET:
        return render(request, 'publications/publications.txt', {
            'publications': publications
        }, content_type='text/plain; charset=UTF-8')

    if 'bibtex' in request.GET:
        return render(request, 'publications/publications.bib', {
            'publications': publications
        }, content_type='text/x-bibtex; charset=UTF-8')

    if 'mods' in request.GET:
        return render(request, 'publications/publications.mods', {
            'publications': publications
        }, content_type='application/xml; charset=UTF-8')

    if 'ris' in request.GET:
        return render(request, 'publications/publications.ris', {
            'publications': publications
        }, content_type='application/x-research-info-systems; charset=UTF-8')

    if 'rss' in request.GET:
        return render(request, 'publications/publications.rss', {
            'url': 'http://' + request.get_host() + request.path,
            'author': fullname,
            'publications': publications
        }, content_type='application/rss+xml; charset=UTF-8')

    # load custom links and files
    populate(publications)

    return render(request, 'publications/author.html', {
        'publications': publications,
        'types': types,
        'author': fullname
    })

publications/views/id.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.shortcuts import render
from publications.models import Type, Publication

def id(request, publication_id):
	publications = Publication.objects.filter(pk=publication_id)

	if 'plain' in request.GET:
		return render(request, 'publications/publications.txt', {
				'publications': publications
			}, content_type='text/plain; charset=UTF-8')

	if 'bibtex' in request.GET:
		return render(request, 'publications/publications.bib', {
				'publications': publications
			}, content_type='text/x-bibtex; charset=UTF-8')

	if 'mods' in request.GET:
		return render(request, 'publications/publications.mods', {
				'publications': publications
			}, content_type='application/xml; charset=UTF-8')

	if 'ris' in request.GET:
		return render(request, 'publications/publications.ris', {
				'publications': publications
			}, content_type='application/x-research-info-systems; charset=UTF-8')

	for publication in publications:
		publication.links = publication.customlink_set.all()
		publication.files = publication.customfile_set.all()

	return render(request, 'publications/id.html', {
			'publications': publications
		})

publications/views/keyword.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.shortcuts import render
from publications.models import Type, Publication, CustomFile, CustomLink
from publications.utils import populate

def keyword(request, keyword):
	keyword = keyword.replace(' ', '+')
	candidates = Publication.objects.filter(keywords__icontains=keyword.split('+')[0], external=False)
	publications = []

	for i, publication in enumerate(candidates):
		if keyword in [k[1] for k in publication.keywords_escaped()]:
			publications.append(publication)

	if 'plain' in request.GET:
		return render(request, 'publications/publications.txt', {
				'publications': publications
			}, content_type='text/plain; charset=UTF-8')

	if 'bibtex' in request.GET:
		return render(request, 'publications/publications.bib', {
				'publications': publications
			}, content_type='text/x-bibtex; charset=UTF-8')

	if 'mods' in request.GET:
		return render(request, 'publications/publications.mods', {
				'publications': publications
			}, content_type='application/xml; charset=UTF-8')

	if 'ris' in request.GET:
		return render(request, 'publications/publications.ris', {
				'publications': publications
			}, content_type='application/x-research-info-systems; charset=UTF-8')

	# load custom links and files
	populate(publications)

	return render(request, 'publications/keyword.html', {
			'publications': publications,
			'keyword': keyword.replace('+', ' ')
		})

publications/views/list.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.http import Http404
from django.shortcuts import render
from publications.models import List, Type, Publication, CustomLink, CustomFile
from publications.utils import populate

def list(request, list):
	list = List.objects.filter(list__iexact=list)

	if not list:
		raise Http404

	list = list[0]
	publications = list.publication_set.all()
	publications = publications.order_by('-year', '-month', '-id')

	if 'plain' in request.GET:
		return render(request, 'publications/publications.txt', {
				'publications': publications
			}, content_type='text/plain; charset=UTF-8')

	if 'bibtex' in request.GET:
		return render(request, 'publications/publications.bib', {
				'publications': publications
			}, content_type='text/x-bibtex; charset=UTF-8')

	if 'mods' in request.GET:
		return render(request, 'publications/publications.mods', {
				'publications': publications
			}, content_type='application/xml; charset=UTF-8')

	if 'ris' in request.GET:
		return render(request, 'publications/publications.ris', {
				'publications': publications
			}, content_type='application/x-research-info-systems; charset=UTF-8')

	if 'rss' in request.GET:
		return render(request, 'publications/publications.rss', {
				'url': 'http://' + request.get_host() + request.path,
				'publications': publications
			}, content_type='application/rss+xml; charset=UTF-8')

	# load custom links and files
	populate(publications)

	return render(request, 'publications/list.html', {
			'list': list,
			'publications': publications
		})

publications/views/unapi.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from publications.models import Publication

def unapi(request):
	"""
	This view implements unAPI 1.0 (see http://unapi.info).
	"""

	id = request.GET.get('id')
	format = request.GET.get('format')

	if format is not None:
		try:
			publications = Publication.objects.filter(pk=int(id))
			
			if not publications:
				raise ValueError

		except ValueError:
			# invalid id
			return HttpResponse('\n'.join([
				'<?xml version="1.0" encoding="UTF-8"?>',
				'<error>Invalid ID.</error>']),
				content_type="application/xml",
				status=404)

		if format == 'bibtex':
			# return BibTex encoded publication
			return render(request, 'publications/publication.bib', {
					'publication': publications[0]
				},
				content_type='text/x-bibtex; charset=UTF-8')

		if format == 'mods':
			# return MODS encoded publication
			return render(request, 'publications/publications.mods', {
					'publications': publications
				},
				content_type='application/xml; charset=UTF-8')

		if format == 'ris':
			# return MODS encoded publication
			return render(request, 'publications/publications.ris', {
					'publications': publications
				},
				content_type='application/x-research-info-systems; charset=UTF-8')

		# invalid format
		return HttpResponse('\n'.join([
			'<?xml version="1.0" encoding="UTF-8"?>',
			'<error>Invalid format.</error>']),
			content_type="application/xml",
			status=406)

	if id is not None:
		return HttpResponse('\n'.join([
			'<?xml version="1.0" encoding="UTF-8"?>',
			'<formats id="{0}">'.format(id),
			'<format name="bibtex" type="text/x-bibtex" />',
			'<format name="ris" type="application/x-research-info-systems" />',
			'<format name="mods" type="application/xml" />',
			'</formats>']), content_type="application/xml")

	return HttpResponse('\n'.join([
		'<?xml version="1.0" encoding="UTF-8"?>',
		'<formats>',
		'<format name="bibtex" type="text/x-bibtex" />',
		'<format name="ris" type="application/x-research-info-systems" />',
		'<format name="mods" type="application/xml" />',
		'</formats>']), content_type="application/xml")

publications/views/year.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.shortcuts import render
from publications.models import Publication, CustomLink, CustomFile
from publications.utils import populate

def year(request, year=None):
	years = []
	publications = Publication.objects.select_related()
	if year:
		publications = publications.filter(year=year, external=False)
	else:
		publications = publications.filter(external=False)
	publications = publications.order_by('-year', '-month', 'authors','-id')

	for publication in publications:
		if publication.type.hidden:
			continue
		if not years or (years[-1][0] != publication.year):
			years.append((publication.year, []))
		years[-1][1].append(publication)

	if 'plain' in request.GET:
		return render(request, 'publications/publications.txt', {
				'publications': sum([y[1] for y in years], [])
			}, content_type='text/plain; charset=UTF-8')

	if 'bibtex' in request.GET:
		return render(request, 'publications/publications.bib', {
				'publications': sum([y[1] for y in years], [])
			}, content_type='text/x-bibtex; charset=UTF-8')

	if 'mods' in request.GET:
		return render(request, 'publications/publications.mods', {
				'publications': sum([y[1] for y in years], [])
			}, content_type='application/xml; charset=UTF-8')

	if 'ris' in request.GET:
		return render(request, 'publications/publications.ris', {
				'publications': sum([y[1] for y in years], [])
			}, content_type='application/x-research-info-systems; charset=UTF-8')

	if 'rss' in request.GET:
		return render(request, 'publications/publications.rss', {
				'url': 'http://' + request.get_host() + request.path,
				'publications': sum([y[1] for y in years], [])
			}, content_type='application/rss+xml; charset=UTF-8')

	# load custom links and files
	populate(publications)

	return render(request, 'publications/years.html', {
			'years': years
		})

publications/templates/publications/author.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="alternate" type="application/rss+xml" title="RSS" href="?rss" />
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications:unapi' %}"/>
{% endblock %}

{% block content %}
	{% if publications %}
		<div class="special_links">
			<a href="?plain">Plain text</a>,
			<a href="?ris">RIS</a>,
			<a href="?bibtex">BibTex</a>
		</div>
		{% for type in types %}
			<h1>{{ type.description }}{% if forloop.first %} by {{ author }}{% endif %}</h1>
			<hr/>
			<div{% if not forloop.last %} style="margin-bottom: 30px;"{% endif %}>
				{% for publication in type.publications %}
					<div{% if not forloop.last %} style="margin-bottom: 20px;"{% endif %}>
						{% include "publications/publication.html" %}
					</div>
				{% endfor %}
			</div>
		{% endfor %}
	{% else %}
		No publications found for {{ author }}.
	{% endif %}
{% endblock %}

publications/templates/publications/id.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications:unapi' %}"/>

	{% for publication in publications %}
		<meta name="citation_date" content="{{ publication.year }}" />
		<meta name="citation_title" content="{{ publication.title }}" />{% for author in publication.authors_list %}
		<meta name="citation_author" content="{{ author }}" />{% endfor %}{% if publication.journal %}
		<meta name="citation_journal_title" content="{{ publication.journal }}" />{% endif %}{% if publication.volume %}
		<meta name="citation_volume" content="{{ publication.volume }}" />{% endif %}{% if publication.issue %}
		<meta name="citation_issue" content="{{ publication.issue }}" />{% endif %}{% if publication.pdf %}
		<meta name="citation_pdf_url" content="{{ MEDIA_URL }}{{ publication.pdf }}" />{% endif %}{% if publication.doi %}
		<meta name="citation_doi" content="{{ publication.doi }}"/>{% endif %}{% if publication.publisher %}
		<meta name="citation_publisher" content="{{ publication.publisher }}"/>{% endif %}{% if publication.institution %}
		<meta name="citation_technical_report_institution" content="{{ publication.institution }}"/>{% endif %}{% if publication.first_page %}
		<meta name="citation_firstpage" content="{{ publication.first_page }}"/>{% endif %}{% if publication.last_page %}
		<meta name="citation_lastpage" content="{{ publication.last_page }}"/>{% endif %}
	{% endfor %}
{% endblock %}

{% block content %}
	<div class="special_links">
		<a href="?plain">Plain text</a>,
		<a href="?ris">RIS</a>,
		<a href="?bibtex">BibTex</a>
	</div>
	{% for publication in publications %}
		<h1>Publication</h1>
		<hr/>
		<div style="margin-bottom: 30px;">
			{% include "publications/publication.html" %}<br/>
		</div>
		<h1>Abstract</h1>
		<hr/>
		<div style="margin-bottom: 30px">
			{{ publication.abstract }}<br/>
		</div>
		<h1>Reference</h1>
		<hr/>
		<pre lang="bibtex">{% include "publications/publication.bib" %}</pre>
	{% endfor %}
{% endblock %}

publications/templates/publications/keyword.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications:unapi' %}"/>
{% endblock %}

{% block content %}
	{% if publications %}
		<div class="special_links">
			<a href="?plain">Plain text</a>,
			<a href="?ris">RIS</a>,
			<a href="?bibtex">BibTex</a>
		</div>
		<h1>Publications with the keyword &quot;{{ keyword }}&quot;</h1>
		<hr/>
		{% for publication in publications %}
			<div{% if not forloop.last %} style="margin-bottom: 20px;"{% endif %}>
				{% include "publications/publication.html" %}
			</div>
		{% endfor %}
	{% else %}
		<h2>Sorry,</h2>
		no publications found with the keyword &quot;{{ keyword }}&quot;.
	{% endif %}
{% endblock %}

publications/templates/publications/list.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications:unapi' %}"/>
{% endblock %}

{% block content %}
	{% if publications %}
		<div class="special_links">
			<a href="?plain">Plain text</a>,
			<a href="?ris">RIS</a>,
			<a href="?bibtex">BibTex</a>
		</div>
		<h1>{{ list.description }}</h1>
		<hr/>
		{% for publication in publications %}
			<div{% if not forloop.last %} style="margin-bottom: 20px;"{% endif %}>
				{% include "publications/publication.html" %}
			</div>
		{% endfor %}
	{% else %}
		<h2>Sorry,</h2>
		no publications found for this list.
	{% endif %}
{% endblock %}

publications/templates/publications/person.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="alternate" type="application/rss+xml" title="RSS" href="?rss" />
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications.views.unapi' %}"/>
{% endblock %}

{% block content %}
	{% if publications %}
		<div class="special_links">
			<a href="?plain">Plain text</a>,
			<a href="?ris">RIS</a>,
			<a href="?bibtex">BibTex</a>
		</div>
		{% for type in types %}
			<h1>{{ type.description }}{% if forloop.first %} by {{ author }}{% endif %}</h1>
			<hr/>
			<div{% if not forloop.last %} style="margin-bottom: 30px;"{% endif %}>
				{% for publication in type.publications %}
					<div{% if not forloop.last %} style="margin-bottom: 20px;"{% endif %}>
						{% include "publications/publication.html" %}
					</div>
				{% endfor %}
			</div>
		{% endfor %}
	{% else %}
		No publications found for {{ author }}.
	{% endif %}
{% endblock %}

publications/templates/publications/publication.html
{% load publication_extras %}

{% if publication.authors_escaped|length > 1 %}
	{% for author, author_escaped in publication.authors_escaped|slice:":1" %}
	<a href="{% url 'publications:author' author_escaped %}" class="author">{{ author }}</a>,
	{% endfor %} <i>et al.</i><br />
{% else %}
	{% for author, author_escaped in publication.authors_escaped %}
	<a href="{% url 'publications:author' author_escaped %}" class="author">{{ author }}</a>{% if not forloop.last %}{% if forloop.revcounter == 2 %}{% if not forloop.first %},{% endif %} and {% else %}, {% endif %}{% endif %}
	{% endfor %}<br />
{% endif %}
<b><a href="{% url 'publications:id' publication.pk %}" class="title">{{ publication.title|tex_parse }}</a></b>
{% if user.is_staff %}
    <a href="{% url 'admin:publications_publication_change' publication.id %}">[EDIT]</a>
{% endif %}
<br/>
{% if publication.journal %}
	<i>{{ publication.journal }}{% if publication.note %} ({{ publication.note }}){% endif %},
	{% if publication.volume %}<b>{{ publication.volume }}</b>{% if publication.number %}({{ publication.number }}){% endif %},{% endif %}
	{% if publication.pages %}{{ publication.pages }},{% endif %}
	{{ publication.year }}{% if publication.doi and 'http' in publication.doi %}; doi:
		<a class="link" rel="external" target="_blank" href="{{ publication.doi }}">{{ publication.doi }}</a>,
	{% elif publication.doi %}; doi:
		<a class="link" rel="external" target="_blank" href="http://dx.doi.org/{{ publication.doi }}">{{ publication.doi }}</a>
	{% endif %}
	</i><br />
{% else %}
	<i>{% if publication.book_title %}{{ publication.book_title }}{% if publication.note %} ({{ publication.note }}){% endif %},{% endif %}
	{% if publication.publisher %}{{ publication.publisher }},{% endif %}
	{% if publication.institution %}{{ publication.institution }},{% endif %}
	{% if publication.pages %}{{ publication.pages }},{% endif %}
	{{ publication.year }}{% if publication.isbn %},
	ISBN {{ publication.isbn }}{% endif %}</i><br />
{% endif %}
{% if publication.keywords %}
	{% for keyword, keyword_escaped in publication.keywords_escaped %}
	<a class="keyword" href="{% url 'publications:keyword' keyword_escaped %}">{{ keyword }}</a>
	{% endfor %}
	<br />
{% endif %}
{% if publication.code %}<a class="link" href="{{ publication.code }}">Code</a>,{% endif %}
{% if publication.url %}<a class="link" rel="external" target="_blank" href="{{ publication.url }}">URL</a>,{% endif %}
{% if not publication.journal and publication.isbn %}<a class="link" rel="external" target="_blank" href="http://isbndb.com/search/all?query={{ publication.isbn }}">ISBN</a>,{% endif %}
{% if publication.pdf %}<a class="link" target="_blank" href="{{ MEDIA_URL }}{{ publication.pdf }}">PDF</a>,{% endif %}
{% for file in publication.files %}
	<a class="link" target="_blank" href="{{ MEDIA_URL }}{{ file.file }}">{{ file.description }}</a>,
{% endfor %}
{% for link in publication.links %}
	<a class="link" target="_blank" rel="external" href="{{ link.url }}">{{ link.description }}</a>,
{% endfor %}
<a href="{% url 'publications:id' publication.pk %}?ris">RIS</a>,
<a href="{% url 'publications:id' publication.pk %}?bibtex">BibTex</a>
<abbr class="unapi-id" title="{{ publication.id }}"></abbr>
<span class="Z3988" title="{{ publication.z3988 }}"></span>

publications/templates/publications/publications.html
{% for publication in publications %}
	<div{% if not forloop.last %} style="margin-bottom: 20px;"{% endif %}>
		{% include "publications/publication.html" %}
	</div>
{% endfor %}

publications/templates/publications/publications_with_thumbnails.html
<table style="width: 100%;">
{% for publication in publications %}
	<tr>
		<td style="width: 100px; padding: 5px 10px 0px 0px; vertical-align: top;">
		{% if publication.thumbnail %}
			{% if publication.code %}
				<a href="{{ publication.code }}"><img src="{{ MEDIA_URL }}{{ publication.thumbnail }}" style="width: 100px; height: 100px;" /></a>
			{% else %}
			<a href="{% url 'publications:id' publication.pk %}"><img src="{{ MEDIA_URL }}{{ publication.thumbnail }}" style="width: 100px; height: 100px;" /></a>
			{% endif %}
		{% endif %}
		</td>
		<td{% if not forloop.last %} style="padding-bottom: 20px; vertical-align: top;"{% endif %}>
			{% include "publications/publication.html" %}
		</td>
	</tr>
{% endfor %}
</table>

publications/templates/publications/years.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="alternate" type="application/rss+xml" title="RSS" href="?rss" />
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications:unapi' %}"/>
{% endblock %}

{% block content %}
	<div class="special_links">
		<a href="?plain">Plain text</a>,
		<a href="?ris">RIS</a>,
		<a href="?bibtex">BibTex</a>
	</div>
	{% for year, publications in years %}
	<a href="{% url 'publications:year' year %}"><h1>{{ year }}</h1></a>
		<hr/>
		<div{% if not forloop.last %} style="margin-bottom: 30px;"{% endif %}>
		{% for publication in publications %}
			<div{% if not forloop.last %} style="margin-bottom: 20px;"{% endif %}>
				{% include "publications/publication.html" %}
			</div>
		{% endfor %}
		</div>
	{% endfor %}
{% endblock %}